### ISSUE TITLE
Wisteria and Driftwood glass trapdoors rendering issue

### ISSUE THREAD

**Issue by Angela** [equinoxrex/-Builder-s-Basics#2]
When Wisteria and Driftwood glass trapdoors are placed on the ground, you can see through the ground through the transparent parts as though you were in spectator mode.

![2020-07-06_21 36 39](https://user-images.githubusercontent.com/47881/86711622-fb64a000-bfd0-11ea-8b81-62208f9b4af9.png)

**Comment by equinoxrex** [comment]
Does this also affect the doors? (when they are flat against a wall)

**Comment by Angela** [comment]
Looks like it does in fact affect the doors as well:

![2020-07-09_14 55 49](https://user-images.githubusercontent.com/47881/87094907-9a1d1680-c1f4-11ea-83cb-85ff3ed2c7cd.png)
